# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='A record determined uniquely by this field.', max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('gender', models.PositiveSmallIntegerField(help_text='See this module constant.')),
            ],
        ),
    ]
