# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(help_text='A record determined uniquely by this field.', max_length=256, unique=True),
        ),
    ]
