# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_sample', '0002_auto_20170424_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(help_text='See this module constant.', max_length=16),
        ),
    ]
